In [1]:
import numpy as np

In [9]:
a = np.array([1,2,3])
b = np.array([1,2])

In [7]:
np.reshape(a,(4,1)) * b

array([[1, 2],
       [2, 4],
       [3, 6],
       [4, 8]])

In [10]:
x = np.array([[1,2,3],[4,5,6]])

In [11]:
x + a

array([[2, 4, 6],
       [5, 7, 9]])

In [13]:
print((x.T + b).T)

[[2 3 4]
 [6 7 8]]
